### ISSUE TITLE
Requesting Access to Interim-CMS

### ISSUE THREAD

**Issue by hughes-dustin** [department-of-veterans-affairs/vagov-content#341]
## Content Area(s)
Please type an "x" in the box that corresponds to your content area.

- [ ] Health Care
- [ ] Disability
- [x ] Education and Training
- [ ] Careers and Employment
- [ ] Pension
- [ ] Housing Assistance
- [ ] Life Insurance
- [ ] Burials and Memorials
- [ ] Records

**Comment by ncksllvn** [comment]
Per this convo, https://github.com/department-of-veterans-affairs/vagov-content/issues/340#issuecomment-477786989, you should already have access, but please ping me if this isn't the case. Thanks @hughes-dustin!
