### ISSUE TITLE
adding non-vet audience callout hub on Education hub page

### ISSUE THREAD

**Issue by jenniferlee-dsva** [department-of-veterans-affairs/vagov-content#507]
@Karak888  and @peggygannon 
We need a non-veteran audience right rail component on the Education hub landing page (similar to what we have in the [Housing hub](https://www.va.gov/housing-assistance/).  See attached screenshot of Housing example. 

I am working to finalize destination urls and actual audience labels with Luke Tickner and will post the content here when it's final (though I can send over draft/in-flight content). @peggygannon will CC you for awareness. 

This request is urgent in that it comes to us escalated and separately, Edu hub goes into CMS content freeze this Wed 7/24. So we need to be live before that day's deploy.

**Comment by Karak888** [comment]
@ncksllvn for awareness..

**Comment by jenniferlee-dsva** [comment]
Okay, vetted info with Luke Tickner. Here is the final content and destination URL for the Edu hub component: 

For the Education hub, we need the content to link to: 

  - heading: Not a Veteran?
    subsections:
      - subhead: "Get education and training information for:"
        links:
        - url: https://www.benefits.va.gov/gibill/school_resources.asp
          label: "School administrators"

@Karak888 @ncksllvn CC @peggygannon 
Please be sure to loop in Peggy to proofread this before it goes live.

**Comment by ncksllvn** [comment]
I opened a PR for this here, https://github.com/department-of-veterans-affairs/vagov-content/pull/508. @peggygannon can you take a look when you have a sec? Feel free to directly make the correction 🙂 

![image](https://user-images.githubusercontent.com/1915775/61665505-27ddba00-aca3-11e9-901c-01b91d61c4c1.png)

**Comment by peggygannon** [comment]
Hello, @ncksllvn, I just approved the PR. Content update looks good.

**Comment by ncksllvn** [comment]
Merged! Will go live during tomorrow's scheduled deployment.

**Comment by Karak888** [comment]
@peggy @ncksllvn as always, thank you for your dedication and work!

**Comment by nedierecel** [comment]
@ncksllvn Please see the GA tracking for the `Not a Veteran` links in the right rail. 

`dataLayer.push({'event': 'nav-not-veteran'});`

@jenniferlee-dsva Within Google Analytics events, this will be output as *Navigation - Not a Veteran - School Administrators*.

**Comment by ncksllvn** [comment]
@nedierecel This link is generated out of a standard template that generates all of the links in the right sidenavs of hub landing pages. Because of that, it would be cleaner on the FE to use the link's values to generate the event data, instead of a special case.

```
dataLayer.push({
  'event':  'hub-rail',
  'hub-rail-action': 'Navigation - Not a Veteran? - School Administrators'
});
```

Do we lose anything by doing it that way, or is this okay? It would also give us insight into all of the activity in those links, instead of just this one case.

**Comment by nedierecel** [comment]
@ncksllvn Please see a few tweaks to the event name. In place of "hub-rail-action", we can leverage an existing dataLayer variable we've used. 

`dataLayer.push({
  'event':  'nav-hub-rail',
  'nav-path': 'Not a Veteran'
});`

I can pull the rest of the information via the Click Text.

**Comment by ncksllvn** [comment]
Thanks @nedierecel! I implemented this. Only catch is that there's a question mark in the nav-path -

```
{ 'event': 'nav-hub-rail', 'nav-path': 'Not a Veteran?' }
```

**Comment by nedierecel** [comment]
Thanks @ncksllvn for collaborating here. I updated the tags in GTM as well. Please see my validation here: 

![image](https://user-images.githubusercontent.com/24525739/61742802-eb24c800-ad61-11e9-94a6-63cc6166d1e4.png)

For a future sprint, I can look at other sections to begin measuring these interactions also.

**Comment by ncksllvn** [comment]
Thank you @nedierecel!!

**Comment by ncksllvn** [comment]
@Karak888 care to close this? 😸

**Comment by Karak888** [comment]
I do @ncksllvn !
