### ISSUE TITLE
Urgent Care Locations Included from Community Care Facility Locator 

### ISSUE THREAD

**Issue by Karak888** [department-of-veterans-affairs/vagov-content#547]
As a Veteran, Family member, Care giver, I need to be able to use the facility locator to search for Urgent Care facilities that are in or near my location, so that I can easilly find the Urgent Care location and type I need.

 **Problem:**
When the Mission Act was launched on 6/6/19, Urgent Care services were removed from the Facility Locator due to incorrect data being returned. 
       _Note:_  The data will supposedly be fixed around 9/10/19. 

**Acceptance Criteria:**
- [ ] Urgent Care is listed in the dropdown for Community Care Facility Locator 
- [ ] Dropdown for service Type includes urgent care locations 
- [ ] Dropdown for service Type includes urgent care locations with Retail 
- [ ] Database will store both retail and non retail Urgent Care Facilities as:
      - [ ] Place of Service (POS) 17:  Urgent Care locations with Retail 
      - [ ] Place of Service:  Urgent Care locations without Retail

**Comment by ncksllvn** [comment]
Issue moved to [department-of-veterans-affairs/va.gov-team #1499](https://github.com/department-of-veterans-affairs/va.gov-team/issues/1499) via [**ZenHub**](https://www.zenhub.com/)
